@startuml Coworking_Booking_System
left to right direction
actor Visitor  
actor User
actor Admin

rectangle "Coworking Booking System" {
  usecase "Login account " as UC_login
  usecase "create account " as UC_register
  usecase "Browse coworking spaces" as UC_Browse
  usecase "Search and filter spaces" as UC_Search
  usecase "View space details" as UC_ViewDetails
  usecase "Book a space" as UC_Book
  usecase "Make a payment" as UC_Pay
  usecase "View booking history" as UC_History
  usecase "Manage profile" as UC_ManageProfile
  usecase "Manage coworking spaces" as UC_ManageSpaces
  usecase "Manage bookings" as UC_ManageBookings
  usecase "Manage users" as UC_ManageUsers

}

Visitor -- UC_Browse
Visitor -- UC_Search
Visitor -- UC_ViewDetails
Visitor -- UC_login
Visitor -- UC_register

User -- UC_Browse
User -- UC_Search
User -- UC_ViewDetails
User -- UC_Book
User -- UC_Pay
User -- UC_History
User -- UC_ManageProfile

Admin -- UC_ManageSpaces
Admin -- UC_ManageBookings
Admin -- UC_ManageUsers
@enduml
